### ISSUE TITLE
Bug: Update the current Workflow file to match the code

### ISSUE THREAD

**Issue by hgminerva** [Xode-DAO/xode-blockchain#10]
Update the current Workflow file to match the code so that we cannot have commit failures in Githug: https://github.com/Xode-DAO/xode-blockchain-template/actions/runs/12149947106/workflow

**Comment by ArneilPaulPolican** [comment]
On the line 26 I think it should be `xode-node` not `parachain-template-node`.
Manual execution
![image](https://github.com/user-attachments/assets/973bc58c-9c80-4aca-bcbb-2aec7644adaf)

**Comment by hgminerva** [comment]
This is done, zombienet.toml will not be used for Github Action while for local development we will use the zombienet-local.toml.  Merge commit: https://github.com/Xode-DAO/xode-blockchain/commit/d0bbe96419e35bcb153388da1ee567a49c2b409d
