### ISSUE TITLE
Enhancement: Remove sudo and replace it with collective members to authorize root access.

### ISSUE THREAD

**Issue by hgminerva** [Xode-DAO/xode-blockchain#12]
We need to remove sudo and replace with a generic collective members that will authorize a user to have root access through a vote.  The same collective members will authorize the spend of treasury through voted proposals.

**Comment by villenaj** [comment]
If we remove `pallet_sudo`, which account will have access to add collective members?

**Comment by hgminerva** [comment]
The council accounts are injected at genesis and can be altered anytime
true membership (next step after we configure the collective)

**Comment by villenaj** [comment]
I'll assume at least half of them will agree.
`pub type EnsureTechnicalCommitteeMajority = EnsureProportionAtLeast<AccountId, TechnicalCommitteeInstance, 1, 2>;`

**Comment by hgminerva** [comment]
2/3, but this will do, we will just make sure that it will compile then we can alter the logic after.

**Comment by villenaj** [comment]
All goods. Will do another PR for removing `pallet_sudo`.
![image](https://github.com/user-attachments/assets/fd500cad-43ce-486a-8db7-b50e48a7b4d9)

**Comment by hgminerva** [comment]
Leave first the pallet_sudo, we will create an issue for the sudo later.

**Comment by hgminerva** [comment]
This is done under PR: https://github.com/Xode-DAO/xode-blockchain/pull/20
