### ISSUE TITLE
Bug: Fix the mock.rs file in pallets/staking/src

### ISSUE THREAD

**Issue by hgminerva** [Xode-DAO/xode-blockchain#29]
Use rust-analyzer to determine the issue in the mock.rs file and fix it.  (See below image)

![Screenshot from 2024-12-14 08-36-02](https://github.com/user-attachments/assets/7a229f17-c5f8-4fde-9efe-6b771760a189)

**Comment by villenaj** [comment]
Are we going to create a mock test or just fix the error?

**Comment by hgminerva** [comment]
@villenaj we are to fix the mock.rs so that we can test.

**Comment by hgminerva** [comment]
@villenaj I am doing this, once done I will need help on the test.

**Comment by hgminerva** [comment]
This is done, we move on to individual test. https://github.com/Xode-DAO/xode-blockchain/commit/df105e2373b04c9f82f476c3e3a1f0c564331978
