### ISSUE TITLE
Documentation: Delegation Process

### ISSUE THREAD

**Issue by hgminerva** [Xode-DAO/xode-blockchain#7]
We need to create a document about delegation. Delegation is the process of staking XON tokens to a known collator or validator node. Any wallet or user can stake XON, which will be added to the total stake of the chosen collator or validator. This stake allows the node to compete for block authorship, and in return, both the node and the delegators will receive rewards.

The document should also identify the percentage allocation of rewards, such as the reward given to the node for authoring blocks and the reward distributed to delegators for staking.

The output of this document will be a detailed list of interface designs for staking delegation for implementation in the existing Xode Staking pallet.

References:
1. https://docs.moonbeam.network/learn/features/staking/ 
3. https://simplystaking.com/moonbeam-staking-guide/
4. https://docs.manta.network/docs/manta-atlantic/Staking/Overview

_Note: The writer must prove that the proposed extrinsic/method is a known function on an existing and operational chain, such as Moonbeam._

Bounty: 500 USDT

**Comment by brymut** [comment]
Hi @hgminerva, is this available for anyone to take on?

**Comment by brymut** [comment]
In which format and where would this document be ideally published? @hgminerva

**Comment by hgminerva** [comment]
Google docs or sheet would do.

**Comment by hgminerva** [comment]
Additional information in the discussion: https://github.com/Xode-DAO/xode-blockchain/discussions/23

**Comment by brymut** [comment]
Thanks for the heads up @hgminerva, I'll factor them in for a draft, today or tomorrow

**Comment by hgminerva** [comment]
Thanks so much.

**Comment by hgminerva** [comment]
We are done with the authors, discussion: https://github.com/Xode-DAO/xode-blockchain/discussions/23, we will create now the rule for assembling it, once done we will move to delegators.

**Comment by hgminerva** [comment]
This is already done and implemented under the last commit: https://github.com/Xode-DAO/xode-blockchain/commit/e4310caf756c7a37067888a489f96e67a2c6d388
